#version: "3.5"
services:
  cli:
    env_file:
      - .env
      - .env.dev
    build:
      context: ./docker/develop/php/cli
    user: ${USER_ID:-1000}
    volumes:
      - ./:/app:rw
    networks:
      - app

  fpm:
    env_file:
      - .env
      - .env.dev
    build:
      context: ./docker/develop/php/fpm
    user: ${USER_ID:-1000}
    volumes:
      - ./:/app:rw
    networks:
      - app

  caddy:
    env_file:
      - .env
      - .env.dev
    image: caddy:alpine
    environment:
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./docker/develop/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./src/web:/app/src/web
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app

  postgres:
    env_file:
      - .env
      - .env.dev
    image: postgres:16-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - app

volumes:
  postgres_db:
  rabbitmq:
  caddy_data:
  caddy_config:

networks:
  app:
